using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Template_DevExpress_By_MFM.Models {
    public partial class SampleData
    {
        public static readonly IEnumerable<OilProduction> OilProductionData = new[] {
            new OilProduction { Year = "Forecast", Country = "Januari", Oil = 456.3 },
            new OilProduction { Year = "Forecast", Country = "Februari", Oil = 352.6 },
            new OilProduction { Year = "Forecast", Country = "Maret", Oil = 191.3 },
            new OilProduction { Year = "Forecast", Country = "April", Oil = 171.2 },
            new OilProduction { Year = "Forecast", Country = "May", Oil = 323.3 },
            new OilProduction { Year = "Forecast", Country = "June", Oil = 300.3 },
            new OilProduction { Year = "Forecast", Country = "July", Oil = 300.3 },
            new OilProduction { Year = "Forecast", Country = "Agustus", Oil = 300.3 },
            new OilProduction { Year = "Forecast", Country = "September", Oil = 300.3 },
            new OilProduction { Year = "Forecast", Country = "Oktober", Oil = 300.3 },
            new OilProduction { Year = "Forecast", Country = "November", Oil = 300.3 },
            new OilProduction { Year = "Forecast", Country = "Desember", Oil = 300.3 },
            new OilProduction { Year = "PO Original", Country = "Januari", Oil = 342.6 },
            new OilProduction { Year = "PO Original", Country = "Februari", Oil = 416.6 },
            new OilProduction { Year = "PO Original", Country = "Maret", Oil = 162.8 },
            new OilProduction { Year = "PO Original", Country = "April", Oil = 146.3 },
            new OilProduction { Year = "PO Original", Country = "May", Oil = 515.9 },
            new OilProduction { Year = "PO Original", Country = "June", Oil = 515.9 },
            new OilProduction { Year = "PO Original", Country = "July", Oil = 300.3 },
            new OilProduction { Year = "PO Original", Country = "Agustus", Oil = 300.3 },
            new OilProduction { Year = "PO Original", Country = "September", Oil = 300.3 },
            new OilProduction { Year = "PO Original", Country = "Oktober", Oil = 300.3 },
            new OilProduction { Year = "PO Original", Country = "November", Oil = 300.3 },
            new OilProduction { Year = "PO Original", Country = "Desember", Oil = 300.3 },
            new OilProduction { Year = "PO Agreed", Country = "Januari", Oil = 192.2 },
            new OilProduction { Year = "PO Agreed", Country = "Februari", Oil = 533.5 },
            new OilProduction { Year = "PO Agreed", Country = "Maret", Oil = 192.6 },
            new OilProduction { Year = "PO Agreed", Country = "April", Oil = 24.2 },
            new OilProduction { Year = "PO Agreed", Country = "May", Oil = 29.2 },
            new OilProduction { Year = "PO Agreed", Country = "June", Oil = 70.2 },
            new OilProduction { Year = "PO Agreed", Country = "July", Oil = 300.3 },
            new OilProduction { Year = "PO Agreed", Country = "Agustus", Oil = 300.3 },
            new OilProduction { Year = "PO Agreed", Country = "September", Oil = 300.3 },
            new OilProduction { Year = "PO Agreed", Country = "Oktober", Oil = 300.3 },
            new OilProduction { Year = "PO Agreed", Country = "November", Oil = 300.3 },
            new OilProduction { Year = "PO Agreed", Country = "Desember", Oil = 300.3 },
            new OilProduction { Year = "Ach. Delivery", Country = "Januari", Oil = 509.8 },
            new OilProduction { Year = "Ach. Delivery", Country = "Februari", Oil = 480.2 },
            new OilProduction { Year = "Ach. Delivery", Country = "Maret", Oil = 74.3 },
            new OilProduction { Year = "Ach. Delivery", Country = "April", Oil = 107.2 },
            new OilProduction { Year = "Ach. Delivery", Country = "May", Oil = 117.2 },
            new OilProduction { Year = "Ach. Delivery", Country = "June", Oil = 127.2 },
            new OilProduction { Year = "Ach. Delivery", Country = "July", Oil = 300.3 },
            new OilProduction { Year = "Ach. Delivery", Country = "Agustus", Oil = 300.3 },
            new OilProduction { Year = "Ach. Delivery", Country = "September", Oil = 300.3 },
            new OilProduction { Year = "Ach. Delivery", Country = "Oktober", Oil = 300.3 },
            new OilProduction { Year = "Ach. Delivery", Country = "November", Oil = 300.3 },
            new OilProduction { Year = "Ach. Delivery", Country = "Desember", Oil = 300.3 },
            new OilProduction { Year = "Yearly Plan", Country = "Januari", Oil = 515.3 },
            new OilProduction { Year = "Yearly Plan", Country = "Februari", Oil = 304.9 },
            new OilProduction { Year = "Yearly Plan", Country = "Maret", Oil = 209.9 },
            new OilProduction { Year = "Yearly Plan", Country = "April", Oil = 157.7 },
            new OilProduction { Year = "Yearly Plan", Country = "May", Oil = 488.5 },
            new OilProduction { Year = "Yearly Plan", Country = "June", Oil = 488.5 },
            new OilProduction { Year = "Yearly Plan", Country = "July", Oil = 300.3 },
            new OilProduction { Year = "Yearly Plan", Country = "Agustus", Oil = 300.3 },
            new OilProduction { Year = "Yearly Plan", Country = "September", Oil = 300.3 },
            new OilProduction { Year = "Yearly Plan", Country = "Oktober", Oil = 300.3 },
            new OilProduction { Year = "Yearly Plan", Country = "November", Oil = 300.3 },
            new OilProduction { Year = "Yearly Plan", Country = "Desember", Oil = 300.3 },
            new OilProduction { Year = "Business Plan GS", Country = "Januari", Oil = 300.5 },
            new OilProduction { Year = "Business Plan GS", Country = "Februari", Oil = 310.3 },
            new OilProduction { Year = "Business Plan GS", Country = "Maret", Oil = 260.4 },
            new OilProduction { Year = "Business Plan GS", Country = "April", Oil = 180.5 },
            new OilProduction { Year = "Business Plan GS", Country = "May", Oil = 300.2 },
            new OilProduction { Year = "Business Plan GS", Country = "June", Oil = 100.2 },
            new OilProduction { Year = "Business Plan GS", Country = "July", Oil = 300.3 },
            new OilProduction { Year = "Business Plan GS", Country = "Agustus", Oil = 300.3 },
            new OilProduction { Year = "Business Plan GS", Country = "September", Oil = 300.3 },
            new OilProduction { Year = "Business Plan GS", Country = "Oktober", Oil = 300.3 },
            new OilProduction { Year = "Business Plan GS", Country = "November", Oil = 300.3 },
            new OilProduction { Year = "Business Plan GS", Country = "Desember", Oil = 300.3 },

        };
    }
}
